
dello-datalake-{deployment_key}-workflow-bu-a:

  description: 'Process data for bu A'
  
  dello-datalake-{deployment_key}-start-trigger:
    id: 'DelloDatalakeWorkflowAStartTrigger'
    type: 'ON_DEMAND'
    initiates: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-1'
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-2'

  dello-datalake-{deployment_key}-trigger-2:
    id: 'DelloDatalakeWorkflowATrigger2'
    type: 'CONDITIONAL'
    dependencies: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-1'
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-2'
    initiates: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-3'

  dello-datalake-{deployment_key}-trigger-3:
    id: 'DelloDatalakeWorkflowATrigger3'
    type: 'CONDITIONAL'
    dependencies: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-3'
    initiates: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-4'
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-5'
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-6'

  dello-datalake-{deployment_key}-trigger-4:
    id: 'DelloDatalakeWorkflowATrigger4'
    type: 'CONDITIONAL'
    dependencies: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-4'
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-5'
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-6'
    initiates: 
      - 'dello-datalake-{deployment_key}-trusted-to-refined-bu-a-7'
