name: AWS Data Engineering

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # DEVELOPMENT DEPLOYMENT

      - name: set env to development
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV

      - name: checkout repository
        uses: actions/checkout@v3

      # - name: cdk diff dev
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'diff'
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      #     AWS_DEFAULT_REGION: 'us-east-1'
      
      - name: bootstrap dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          cdk bootstrap 
      
      - name: cdk deploy dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: 'us-east-1'
      
      # PRODUTION DEPLOYMENT

      - name: set env to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
      
      # - name: cdk diff prod
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'diff'
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      #     AWS_DEFAULT_REGION: 'us-east-1'
       
      # - name: bootstrap prod
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   run: |
      #     cdk bootstrap

      - name: cdk deploy prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEFAULT_REGION: 'us-east-1'
