# Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
# --app is required either in command-line, in cdk.json or in ~/.cdk.json
# bootstrap

name: AWS Data Engineering

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout repository
        uses: actions/checkout@v3

      

      # DEVELOPMENT DEPLOYMENT

      - name: set envs to development
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
      
      - name: s3 upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV}}
          aws_bucket: 'dello-datalake-dev-utilities-339712827658-us-east-1'
          source_dir: 'aws_data_engineering/glue_jobs/scripts'
          destination_dir: 'glue_jobs/scripts'

      - name: cdk diff dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: youyo/aws-cdk-github-actions@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: 'us-east-1'
        with:
          cdk_subcommand: 'diff'
          actions_comment: false
 
      - name: cdk deploy dev DellotechBucketsDatalakeStack
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: youyo/aws-cdk-github-actions@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: 'us-east-1'
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'DellotechBucketsDatalakeStack'
          actions_comment: false

      - name: cdk deploy dev DellotechGlueJobsDatalakeStack
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: youyo/aws-cdk-github-actions@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: 'us-east-1'
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          cdk_stack: 'DellotechGlueJobsDatalakeStack'
          actions_comment: false
      
      # PRODUCTION DEPLOYMENT

      - name: set envs to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV

      - name: cdk diff prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: youyo/aws-cdk-github-actions@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEFAULT_REGION: 'us-east-1'
        with:
          cdk_subcommand: 'diff'
          actions_comment: false
 
      - name: cdk deploy prod DellotechBucketsDatalakeStack
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: youyo/aws-cdk-github-actions@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEFAULT_REGION: 'us-east-1'
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'DellotechBucketsDatalakeStack'
          actions_comment: false

      - name: cdk deploy prod DellotechGlueJobsDatalakeStack
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: youyo/aws-cdk-github-actions@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEFAULT_REGION: 'us-east-1'
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          cdk_stack: 'DellotechGlueJobsDatalakeStack'
          actions_comment: false