
name: AWS Data Engineering

on:

  push:
    branches: [ "develop" ]

  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:

  deploy_dev:

    runs-on: ubuntu-latest

    steps:
      
      - name: Set env to development
        run: |
         echo "ENVIRONMENT=dev" >> $GITHUB_ENV
         echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
   

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEFAULT_REGION: 'us-east-1'

      # - name: cdk deploy
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'deploy'
      #     cdk_stack: 'AwsDataEngineeringStack'
      #     cdk_args: '--require-approval never'
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'us-east-1'
# 
      # - name: cdk synth
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'synth'
      #     cdk_version: '2.118.0'
      #     working_dir: "/"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'us-east-1'
