# Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
# --app is required either in command-line, in cdk.json or in ~/.cdk.json
# bootstrap

name: AWS Data Engineering

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
      - name: set environment variables
        run: |
          if [ "${{ github.event_name }}" == 'push' ]; then
            if [ "${{ github.ref }}" == 'refs/heads/develop' ]; then
              echo "ENVIRONMENT=dev" >> $GITHUB_ENV
              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
              echo ENVIRONMENT=dev
            elif [ "${{ github.ref }}" == 'refs/heads/master' ]; then
              echo "ENVIRONMENT=prod" >> $GITHUB_ENV
              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
              echo ENVIRONMENT=prod
            fi
          fi

      - name: checkout repository
        uses: actions/checkout@v3

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: false

      - name: cdk deploy DellotechBucketsDatalakeStack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'DellotechBucketsDatalakeStack'
          actions_comment: false

      - name: cdk deploy DellotechGlueJobsDatalakeStack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'DellotechGlueJobsDatalakeStack'
          cdk_args: '--require-approval never'
          actions_comment: false
