
name: AWS Data Engineering

on:

  push:
    branches: [ "develop" , "master" ]

  pull_request:
    branches: [ "develop" , "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::975050223655:role/github-actions-cdk
          aws-region: us-east-1