
name: AWS Data Engineering

on:

  push:
    branches: [ "develop" , "master" ]

  pull_request:
    branches: [ "develop" , "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Create variables according to the branch
    - name: Set env to development
      if: endsWith(github.ref, '/develop')
      run: |
        echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        echo "ACCOUNT_ID='339712827658'" >> $GITHUB_ENV
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: |
       echo "ENVIRONMENT=prod" >> $GITHUB_ENV
       echo "ACCOUNT_ID='975050223655'" >> $GITHUB_ENV

    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

  test: 
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Test
        run: |
          python -m pytest
  
  deploy: 

    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy Architecture
        run: |
          cdk deploy
    
